declare const ACTION_OK: ACTION_OK;
declare const ACTION_ERR_FULL: ACTION_ERR_FULL;
declare const ACTION_ERR_NOT_ENOUGH_RESOURCES: ACTION_ERR_NOT_ENOUGH_RESOURCES;
declare const ACTION_ERR_NOT_FOUND: ACTION_ERR_NOT_FOUND;

type ActionReturnCode = ACTION_OK | ACTION_ERR_FULL | ACTION_ERR_NOT_ENOUGH_RESOURCES | ACTION_ERR_NOT_FOUND;
type ACTION_OK = 0;
type ACTION_ERR_FULL = -1;
type ACTION_ERR_NOT_ENOUGH_RESOURCES = -2;
type ACTION_ERR_NOT_FOUND = -3;
