declare const ACTION_DONE: ACTION_DONE;
declare const ACTION_CONT: ACTION_CONT;
declare const ACTION_ERR_FULL: ACTION_ERR_FULL;
declare const ACTION_ERR_NOT_ENOUGH_RESOURCES: ACTION_ERR_NOT_ENOUGH_RESOURCES;
declare const ACTION_ERR_NOT_FOUND: ACTION_ERR_NOT_FOUND;
declare const ACTION_ERR_USE_FALLBACK: ACTION_ERR_USE_FALLBACK;

type ActionReturnCode =
  | ACTION_DONE
  | ACTION_CONT
  | ACTION_ERR_FULL
  | ACTION_ERR_NOT_ENOUGH_RESOURCES
  | ACTION_ERR_NOT_FOUND
  | ACTION_ERR_USE_FALLBACK;

type ACTION_DONE = 1;
type ACTION_CONT = 0;
type ACTION_ERR_FULL = -1;
type ACTION_ERR_NOT_ENOUGH_RESOURCES = -2;
type ACTION_ERR_NOT_FOUND = -3;
type ACTION_ERR_USE_FALLBACK = -4;
