declare const ACTION_DONE: ACTION_DONE;
declare const ACTION_IN_PROGRESS: ACTION_IN_PROGRESS;
declare const ACTION_ERR_MOVE_ON: ACTION_ERR_MOVE_ON;
declare const ACTION_ERR_USE_FALLBACK: ACTION_ERR_USE_FALLBACK;
declare const ACTION_ERR_DROP_TASK_LIST: ACTION_ERR_DROP_TASK_LIST;
declare const ACTION_ERR_DROP_TASK_LIST_AFTER_FALLBACK: ACTION_ERR_DROP_TASK_LIST_AFTER_FALLBACK;

type ActionReturnCode =
  | ACTION_DONE
  | ACTION_IN_PROGRESS
  | ACTION_ERR_MOVE_ON
  | ACTION_ERR_USE_FALLBACK
  | ACTION_ERR_DROP_TASK_LIST
  | ACTION_ERR_DROP_TASK_LIST_AFTER_FALLBACK;

type ACTION_DONE = 1;
type ACTION_IN_PROGRESS = 0;
type ACTION_ERR_MOVE_ON = -1;
type ACTION_ERR_USE_FALLBACK = -2;
type ACTION_ERR_DROP_TASK_LIST = -3;
type ACTION_ERR_DROP_TASK_LIST_AFTER_FALLBACK = -4;
