export const ACTION_OK: ACTION_OK = 0;
export const ACTION_ERR_FULL: ACTION_ERR_FULL = -1;
export const ACTION_ERR_NOT_ENOUGH_RESOURCES: ACTION_ERR_NOT_ENOUGH_RESOURCES = -2;
export const ACTION_ERR_NOT_FOUND: ACTION_ERR_NOT_FOUND = -3;
