export const ACTION_DONE: ACTION_DONE = 1;
export const ACTION_IN_PROGRESS: ACTION_IN_PROGRESS = 0;
export const ACTION_ERR_MOVE_ON: ACTION_ERR_MOVE_ON = -1;
export const ACTION_ERR_USE_FALLBACK: ACTION_ERR_USE_FALLBACK = -2;
export const ACTION_ERR_DROP_TASK_LIST: ACTION_ERR_DROP_TASK_LIST = -3;
export const ACTION_ERR_DROP_TASK_LIST_AFTER_FALLBACK: ACTION_ERR_DROP_TASK_LIST_AFTER_FALLBACK = -4;
